### ISSUE TITLE
the ability to add an entire product to your favorites

### ISSUE THREAD

**Issue by Wjxfi** [SuhasDissa/Food-E-App#48]

**Comment by SuhasDissa** [comment]
Hey there!

It's possible to add an option to mark food products as favorite.
However, I'm still not sure where to put it. I don't think it would be a good idea to put it alongside favorite additives, since those are two different things. And adding another page just for favorite food products would be a bad user experience.

If you have any suggestions, I'd love to hear them. Thanks!
