### ISSUE TITLE
[Bug] Themed / Monochrome app icon not working

### ISSUE THREAD

**Issue by sebastien46** [SuhasDissa/Food-E-App#51]
I saw the code & monochrome app icon seems to be implemented, however the icon does not show up as monochrome in the launcher.

Device : Google Pixel 7
OS: GrapheneOS ( Android 13 )

**Comment by SuhasDissa** [comment]
Can you confirm that themed app icons are enabled in your phone?

It seems to work fine on all the phones I have tested. (I'm currently running Samsung OneUI android 13)

**Comment by SuhasDissa** [comment]
### Here's a screenshot

<img src="https://github.com/SuhasDissa/Food-E-App/assets/64766434/e3c453dc-b6eb-406f-a294-b481e73a060c" width="30%">

**Comment by sebastien46** [comment]
Here it is on my launcher next to stock GrapheneOS Camera App for reference:

![IMG_20230723_180245 1](https://github.com/SuhasDissa/Food-E-App/assets/57289288/7c9128f5-8fcb-4350-a11b-03442cdf5d55)

**Comment by SuhasDissa** [comment]
[Food-E bugfix #51.zip](https://github.com/SuhasDissa/Food-E-App/files/12139557/Food-E.bugfix.51.zip)

Hi there,
I think I found what's causing this bug and was able to fix it. I currently don't have any Pixel device to test it.
Can you please try this app and let me know if the issue is fixed or not.
Thank you,

**Comment by sebastien46** [comment]
It works now. Thank and have a nice day.
