### ISSUE TITLE
use cloud translation to "packaging", "categories", "labels", "ingredients", "allergens" in food products

### ISSUE THREAD

**Issue by Wjxfi** [SuhasDissa/Food-E-App#57]
use cloud translation to "packaging", "categories", "labels", "ingredients", "allergens" in food products

**Comment by SuhasDissa** [comment]
I'm sorry to say that I couldn't translate those data using the cloud translation feature. It turned out to be harder than I thought.
I think the best thing to do would be to wait for OpenFoodFacts to translate their data themselves.

I'm closing this issue as not planned. But I'm always looking forward to make it happen in the future.
